---
- hosts: all
  become: true
  vars: 
    masterip: "{{ mip }}"

  tasks: 
    - name: Create repository for kubernetes
      yum_repository: 
        name: kubernetes
        description:  kubernetes
        file: kuberepo
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgcheck: yes
        enabled: yes
        repo_gpgcheck: yes
        gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"


    - name: Install kubernetes base packages
      yum:   
        name: "{{ item }}"
        state: latest
      with_items: 
        - "kubelet"
        - "kubeadm"
        - "kubectl"
        
    - name: Start and enable Kubelet service 
      service: 
       name: kubelet
       state: started
       enabled: yes
    
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644 

    - name: Install Kubernets compatible Docker 
      yum: 
        name: docker-ce-18.06.1.ce-3.el7*
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
       

    - name: Disable SELinux 
      selinux:
        policy: targeted
        state: permissive 

    - name: Disable SWAP
      command: "{{ item }}" 
      with_items: 
        - "sed -i '/swap/d' /etc/fstab"
        - "swapoff -a"

    - name: Initialize kubernetes cluster 
      command: "kubeadm init –pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address='{{ masterip }}'"
      register: initialize_clus
      delegate_to: "{{ item }}" 
      with_items: "{{ groups['master'] }}"

    - debug: msg={{ initialize_clus }}

    - name: Check Status of Cluster
      command: kubectl get pods --all-namespaces
      register: clus_stat
      delegate_to: "{{ item }}" 
      with_items: "{{ groups['master'] }}"
  
    - debug: msg={{ clus_stat }}
  

    - name: Setup Pod Network
      command: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
      register: podnw
      delegate_to: "{{ item }}" 
      with_items: "{{ groups['master'] }}"
      
    - debug: msg={{ podnw }}


    - name: Check Status of Cluster
      command: kubectl get pods --all-namespaces
      register: clus_stat
      delegate_to: "{{ item }}" 
      with_items: "{{ groups['master'] }}"
  
    - debug: msg={{ clus_stat }}
  
 
    - name: Manage Cluster as Regular User
      shell: "{{ item }}"
      with_items: 
        - "mkdir -p $HOME/.kube"
        - "cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
        - "chown $(id -u):$(id -g) $HOME/.kube/config"
      delegate_to: "{{ item }}" 
      with_items: "{{ groups['master'] }}"


    - name: Get token list 
      shell: kubeadm token list 
      register: kubjoin
      delegate_to: "{{ item }}" 
      with_items: "{{ groups['master'] }}"

    - debug: msg={{ kubjoin }}
  
    - name: join worker node 
      command: "kubeadm join '{{ masterip }}':6443 --token '{{ kubjoin }}'  --discovery-token-unsafe-skip-ca-verification"
      delegate_to: "{{ item }}" 
      with_items: "{{ groups['node1'] }}"
